### ISSUE TITLE
view form data not possible with non-admin users?

### ISSUE THREAD

**Issue by fritzmg** [terminal42/contao-leads#18]
I noticed in a Contao installation, that non-admin users are not able to view the form data of a leads entry in the backend ("Formulardaten der Anfrage ID _xx_ anzeigen" in german). When you click on it, it just shows "An error occurred!" in red. The backend users have all rights regarding the leads extension enabled, i.e.:

* the Backend module
* the tables `tl_lead`, `tl_lead_data`, and `tl_lead_export`
* within `tl_lead_export` all fields

As far as I can see, there are no additional rights I can grant to the user. Is viewing the form data really only possible as an admin right now?

As a workaround the users currently use the information icon right next to the view form data button.

**Comment by aschempp** [comment]
You must give the user access to the respective form. Not to the form generator though if you don't need that.

**Comment by fritzmg** [comment]
But the users do have access to these forms (they also have access to `tl_form` and `tl_form_field` and every field of `tl_form` and `tl_form_field`, in case it matters).

**Comment by aschempp** [comment]
No. There is a configuration for **the forms**, not the tables ;)

**Comment by fritzmg** [comment]
Yes I know, and the permission is set for the forms as well, yet the users cannot access the data (only via Contao's information button).

**Comment by aschempp** [comment]
> only via Contao's information button

?

**Comment by fritzmg** [comment]
I meant this one: http://demo.contao.org/system/themes/default/images/show.gif
Currently the backend users can view the information of the entry only via 
`?do=lead&master=…&key=show&id=…&popup=1` 
and not via 
`?do=lead&master=…&table=tl_lead_data&id=…`
even though the users have all the rights set for the forms and leads.

**Comment by stefanschleich** [comment]
I having the same issue. To verify I created a new user group and gave it all available permissions. Still nothing. This is the code that generates the log message:

```
if (!is_array($objUser->forms)) {
    \System::log('Not enough permissions to access leads data ID "'.\Input::get('id').'"', __METHOD__, TL_ERROR);
    $this->redirect('contao/main.php?act=error');
}
```

**Comment by fritzmg** [comment]
No, it's actually the database query that's wrong:
```php
$objLeads = \Database::getInstance()->prepare("SELECT master_id FROM tl_lead WHERE id=(SELECT pid FROM tl_lead_data WHERE id=?)")
                                            ->limit(1)
                                            ->execute(\Input::get('id'));
```
The ID given in the query string is already a `tl_lead` ID, it's not a `tl_lead_data` ID. Thus the query always returns zero rows.

**Comment by stefanschleich** [comment]
Any news on this?

**Comment by aschempp** [comment]
fixed in 13a0e0e

**Comment by fritzmg** [comment]
@aschempp that doesn't actually fix the problem. The problem is with this code in [dca/tl_lead_data.php](https://github.com/terminal42/contao-leads/blob/master/dca/tl_lead_data.php#L122):
```php
$objLeads = \Database::getInstance()->prepare("SELECT master_id FROM tl_lead WHERE id=(SELECT pid FROM tl_lead_data WHERE id=?)")
                                    ->limit(1)
                                    ->execute(\Input::get('id'));

if (!$objLeads->numRows || !in_array($objLeads->master_id, $objUser->forms)) {
    \System::log('Not enough permissions to access leads data ID "'.\Input::get('id').'"', __METHOD__, TL_ERROR);
    $this->redirect('contao/main.php?act=error');
}
```
`\Input::get('id')` is a `tl_lead` ID, not a `tl_lead_data` ID. You need to change the query to
```php
$objLeads = \Database::getInstance()->prepare("SELECT master_id FROM tl_lead WHERE id=?")
                                    ->limit(1)
                                    ->execute(\Input::get('id'));
```

**Comment by fritzmg** [comment]
This problem still persists in contao-leads `1.2.1`. As I said, you need to change the aforementioned database query.
